### ISSUE TITLE
"GenerateStaticWebAsssetsPropsFile" task failed unexpectedly.

### ISSUE THREAD

**Issue by netrunner1987** [Netcode-Hub/DemoBlazorWASMCustomAuthenticationWithJwtAndAuthStateProvider#1]
Compliing the client I get this error.

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "GenerateStaticWebAsssetsPropsFile" task failed unexpectedly.
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\mclin\source\repos\DemoBlazorWASMCustomAuthenticationWithJwtAndAuthStateProvider-master\DemoRegistrationEncryptionUsingRandomNumberAndSalt\obj\Debug\net7.0\staticwebassets\msbuild.DemoRegistrationEncryptionUsingRandomNumberAndSalt.Microsoft.AspNetCore.StaticWebAssets.props'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at Microsoft.AspNetCore.StaticWebAssets.Tasks.GenerateStaticWebAsssetsPropsFile.ExecuteCore()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	DemoRegistrationEncryptionUsingRandomNumberAndSalt	C:\Program Files\dotnet\sdk\8.0.100-preview.7.23376.3\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.Pack.targets	136

**Comment by Netcode-Hub** [comment]
Hello friend, thanks again for contacting Netcode-Hub,
Could not find a part of the path 'C:\Users\mclin\source\repos\DemoBlazorWASMCustomAuthenticationWithJwtAndAuthStateProvider-master\DemoRegistrationEncryptionUsingRandomNumberAndSalt\obj\Debug\net7.0\staticwebassets\msbuild.DemoRegistrationEncryptionUsingRandomNumberAndSalt.Microsoft.AspNetCore.StaticWebAssets.props'.

Please clean your:

  1.  Solution
  2.  Project
  3.  rebuild project
  4.  rebuild solution

Thanks...

________________________________
From: netrunner1987 ***@***.***>
Sent: Sunday, August 27, 2023 9:41 PM
To: Netcode-Hub/DemoBlazorWASMCustomAuthenticationWithJwtAndAuthStateProvider ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Netcode-Hub/DemoBlazorWASMCustomAuthenticationWithJwtAndAuthStateProvider] "GenerateStaticWebAsssetsPropsFile" task failed unexpectedly. (Issue #1)


Compliing the client I get this error.

Severity Code Description Project File Line Suppression State
Error MSB4018 The "GenerateStaticWebAsssetsPropsFile" task failed unexpectedly.
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\mclin\source\repos\DemoBlazorWASMCustomAuthenticationWithJwtAndAuthStateProvider-master\DemoRegistrationEncryptionUsingRandomNumberAndSalt\obj\Debug\net7.0\staticwebassets\msbuild.DemoRegistrationEncryptionUsingRandomNumberAndSalt.Microsoft.AspNetCore.StaticWebAssets.props'.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
at Microsoft.AspNetCore.StaticWebAssets.Tasks.GenerateStaticWebAsssetsPropsFile.ExecuteCore()
at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
at Microsoft.Build.BackEnd.TaskBuilder.d__26.MoveNext() DemoRegistrationEncryptionUsingRandomNumberAndSalt C:\Program Files\dotnet\sdk\8.0.100-preview.7.23376.3\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.Pack.targets 136
